// OptionProps 에서 받아와서 삭제 예정
export const filterOptions = {
  options1: [
    '서울',
    '부산',
    '대구',
    '인천',
    '광주',
    '대전',
    '울산',
    '세종',
    '경기',
    '강원',
    '충북',
    '충남',
    '전북',
    '전남',
    '경북',
    '경남',
    '제주',
  ],
  options2: ['축구', '야구', '테니스', '농구', '탁구', '러닝', '자전거'],
  options3: ['남', '여', '남녀 모두'],
  options4: [
    '루키',
    '비기너 Low',
    '비기너 Medium',
    '비기너 High',
    '아마추어 Low',
    '아마추어 Medium',
    '아마추어 High',
    '세미프로 Low',
    '세미프로 High',
    '프로',
  ],
  options5: [
    '루키',
    '비기너 Low',
    '비기너 Medium',
    '비기너 High',
    '아마추어 Low',
    '아마추어 Medium',
    '아마추어 High',
    '세미프로 Low',
    '세미프로 High',
    '프로',
  ],
}
